# core/error_codes.py


class ErrorCode:
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE"
    REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND"
    INVALID_RESET_CODE = "INVALID_RESET_CODE"
